### ISSUE TITLE
List resources for multiple servers

### ISSUE THREAD

**Issue by kokarn** [GleSYS/API#11]
Do you have any plans to implement an array option to say ```server/status```?

This would probably reduce the load a lot, especially for dashboards displaying multiple servers.

Thanks for an otherwise great api

**Comment by emilv** [comment]
What you are asking for is really batching, one of the most understated features in REST APIs. It seems as if *everyone* develops their APIs without batching in mind. The GleSYS control panel itself does not do batching but instead queries email account storage usage for each account in order, which means it can take a while before the usage is displayed in the control panel...

I agree that the API should have batching, preferably in a generic sense where you can send in multiple commands at once regardless of type. For us this could help us update account quotas in one single call.

**Comment by wecc** [comment]
@kokarn Sorry for the late reply! We're looking at JSON API (http://jsonapi.org/) and the possibilities it gives when it comes to filtering and side-loading via includes. In your scenario I'd imagine a request to something like `/servers?include=status` would give you the result you're looking for. Or for two specific servers only: `/servers?filter[id]=vz12345,vz67890&include=status`. Sparse Fieldsets would also give you the option to optimize results further.

@emilv I hear you and I agree. Real world examples of what you'd like to be able to do would be greatly appreciated! I'm following http://jsonapi.org/extensions/jsonpatch/ with great interest.

**Comment by kokarn** [comment]
No worries! I understand this part of your business isn't really the highest priority :)

Yeah, both those endpoints would be great. I'm sure there are a lot of people who want to use that data in their own control systems and dashboards. Any plans to update the data more than once per minute?

**Comment by emilv** [comment]
@wecc We have a real world example! We manage allocated email account quota automatically for hundreds of accounts on hundreds of domains, upgrading and downgrading quota when needed. This is how it works:

1. Fetch list of domains (1 API call)
2. Fetch email accounts per domain (100s of API calls, 1 per domain, even when domain does not have any accounts)
3. Fetch account quota and usage (100s of API calls, 1 per account)
4. Set new global quota (1 API call if needed)
5. Set new account quota (a handful of API calls depending on how many accounts need change, usually none...)

With batching we could have done step 2, 3 and 5 in one API call each. GleSYS would also benefit from batching for step 3 because that operation is done by the control panel as well.

**Comment by emilv** [comment]
On the other hand, our use case could be eliminated entirely if GleSYS as a cloud provider did this automatically...

**Comment by wecc** [comment]
@emilv That's a great use-case. Thanks!

We _will_ be moving towards JSON API and in a perfect world you should be able to simply call `/email-accounts?include=quota` instead of those 100s + 100s of API calls, effectively replace 1-3 with a single API call.

"Floating" quotas based on the global quota is something we've discussed, I'll make sure to shine some more light on it.

**Comment by wecc** [comment]
This has been moved to our internal tracker as we work towards the next generation of our API. Closing this issue.
