### ISSUE TITLE
New status code for server/edit? Not mentioned in documentation.

### ISSUE THREAD

**Issue by liljefelt** [glesys/API#36]
Hi,

Did the server/edit response status code change recently?
I'm getting an incrementing status code with the status text "Server update scheduled".

I didn't see this (recent?) behaviour mentioned in the API documentation.
Any update on this would be appreciated.

Thanks.

**Comment by wecc** [comment]
Hi!

Thank you so much for bringing this to our attention. This is indeed a bug introduced in a recent change related to status codes. What you're seeing is actually the transaction ID for the requested change instead of the `200 OK` status code.

I've submitted a fix and it should go live as soon as it has passed the review process. I'll let you know when!

**Comment by liljefelt** [comment]
Great, thanks!

I solved it temporarily by adding a check for the status text string "Server update scheduled".

**Comment by wecc** [comment]
The fix for this is now live and the status codes should be correct again 🙌 

Thanks again for letting us know!
