### ISSUE TITLE
Please add support for changing the template value

### ISSUE THREAD

**Issue by xmstspider** [glesys/API#38]
Hi,

we migrated server from CentOS to AlmaLinux but the template stil says "CentOS 8". You customer service told me that there is no option to change this via API or dashboard, so I would like to ask for this feature.

In server detail, it is about this block:
``
      "templatename": "CentOS 8",
      "initialtemplate": {
        "id": "<uuid>",
        "name": "CentOS 8",
        "currenttags": [
          "centos",
          "centos-8"
        ]
      },
``
I tried to call this API: 

``
curl -H "Accept: application/json" -X POST --basic -u $id:$token -d "serverid=$server_id&template=AlmaLinux 8" https://api.glesys.com/server/edit/
``

but it did not change anything.

**Comment by wecc** [comment]
Hi @xmstspider!

We are in the progress of renaming the `templatename` field to `operatingsystem` and have it be updatable using Cloud/API since this value might not always represent the truth due to reinstall, upgrade etc. However, there are still some logic depending on this field to not be editable that we need to get rid of before we can complete the transition.

Feel free to send a request to support@glesys.se to change this field manually (please provide the server ID and what value you want instead).

Hope that helps for now!
